name: GOLF GUFF Ring CI

on:
  push:
    branches:
      - main
      - 'saelis/**'
  pull_request:

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DGUFF_BUILD_TESTS=ON
      - name: Build
        run: cmake --build build --config Release --parallel
      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure
